### ISSUE TITLE
nuttx flashing on pixhawk 2.4.8(STM32F427V board)

### ISSUE THREAD

**Issue by amitmanish** [rohiniku/NuttX-nuttx-boards#1]
Hi rohiniku,
I wanted to learn nuttx programming. I have a pixhawk board and i see px4 uses nuttx in their firmware for pixhawk flight controller. Could you also add px4fmu-v2 board to nuttx so that it can be flashed in pixhawk board.

**Comment by rohiniku** [comment]
Hi amitmanish,

Do you want to operate plain NuttX with px4fmu-v2 board instead of pixhawk firmware?

I have not done development of PX4 Firmware or NuttX for quite a long time already so I can not answer clearly...
Perhaps, if you port the PX4 Firmware's px4fmu-v2 board configuration (platforms/nuttx/nuttx-configs/px4fmu-v2) to the NuttX configs directory, I think that is possible.

As you may know, the original repository is here.

[PX4 Firmware](https://github.com/PX4/Firmware/tree/master/platforms/nuttx/nuttx-configs
)

[NuttX](https://bitbucket.org/nuttx/nuttx/src/d6e563312b727964d274f46f13edfe48c6590f72/configs/?at=master)

**Comment by amitmanish** [comment]
Thanks for reply. I tried that with plain nuttx and i was successful in adding pixhawk board and using make menuconfig option of nuttx to configure board but could not build nuttx as it was showing some error in building. May be it is compatibility issue.

**Comment by amitmanish** [comment]
Isnt there any tutorial on understanding px4 from basics cause i wanted to start from the beginning.
